version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: ${PORT}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_URI_TEST: ${MONGODB_URI_TEST}
      MONGODB_DB_NAME: ${MONGODB_DB_NAME}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASS: ${MONGODB_PASS}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
      MONGO_INITDB_PORT: ${MONGODB_PORT}
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME}
    # volumes:
    #   - data:/data/db
    command: ["--auth"]
    volumes:
      - data:/data/db
      - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-users.sh:ro
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    env_file:
      - .env
volumes:
  data:
    driver: local
