name: "test"

# **What it does**: Ensures tests are finishing successfully.
# **Why we have it**: Gotta catch em all badges.
# **Who does it impact**: Nothing.

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  buildandtest:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up npm and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Build
        run: yarn test
